name: demo_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  faker: ^2.1.0
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  bcrypt: 1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mongo_dart: ^0.10.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/Studio-Project-nobg.png
    - assets/images/2x2_YNSON.png
    - assets/images/bmp.png
